steps:
- uses: docker://docker:19.03.3
  args: [build, -t, 'getpopper/$_STEP:$_VERSION', '--build-arg', 'VERSION=$_VERSION', '$_STEP/']
- uses: "ivotron/bin/filter@master"
  args: [branch, master]
- uses: docker://docker:19.03.3
  runs: [/bin/sh]
  args: [-c,
    'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
     docker push getpopper/$_STEP:$_VERSION'
  ]
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
