---
dist: xenial
language: python
python: 3.7
services: docker
env:
- STEP=geni VERSION=v0.9.9.2
- STEP=ansible VERSION=2.7.17
- STEP=ansible VERSION=2.8.11
- STEP=ansible VERSION=2.9.7
- STEP=ceph-ansible VERSION=v3.2.42
- STEP=ceph-ansible VERSION=v4.0.22
- STEP=csvtool VERSION=2.4
- STEP=heroku-cli VERSION=7.42.1-4.2.1 CLI_VERSION=7.42.1 LIB_VERSION=4.2.1
install:
- git clone https://github.com/getpopper/popper /tmp/popper
- pip install /tmp/popper/cli
script:
- popper run --substitution _STEP=$STEP --substitution _VERSION=$VERSION --substitution _CLI_VERSION=$CLI_VERSION --substitution _LIB_VERSION=$LIB_VERSION -f .ci.yml
